INSERT INTO `idheasIkari`.`actosN3Catalogo`
(`actoN3Id`,
`descripcion`,
`actosN2Catalogo_actoN2Id`,
`notas`)
VALUES
(1,'Desaparición forzada',1,''),
(2,'Ejecución',1,''),
(3,'Ejecución judicial por aplicación de la pena de muerte',1,''),
(4,'Genocidio',1,''),
(5,'Masacre',1,''),
(6,'Muerte bajo custodia',1,''),
(7,'Muerte en contexto de operaciones militares',1,'Excepto los operativos militares de seguridad pública'),
(8,'Muerte en contexto de operativos de seguridad pública',1,''),
(9,'Muerte resultado de negligencia',1,''),
(10,'Muerte resultado de otras VDH',1,''),
(11,'Muerte sospechosa',1,''),
(12,'Muerte violenta',1,''),
(13,'Agresión sexual',2,''),
(14,'Agresiones físicas',2,''),
(15,'Hostigamiento sexual',2,''),
(16,'Intento de violación sexual',2,''),
(17,'Intimidación',2,''),
(18,'Tortura',2,''),
(19,'Tratos crueles, inhumanos o degradantes',2,''),
(20,'Uso desproporcionado o indebido de la fuerza pública',2,'Se utiliza independientemente de si el uso de la fuerza es justificado o no, legal o no, cuando este uso de la fuerza es desproporcionado (cuando no es proporcional a lo estrictamente necesario). La utilización de la fuerza debe ser una medida excepcional. Cfr. Código de conducta para funcionarios encargados de hacer cumplir la ley. Adoptado por la Asamblea General en su resolución 34/169, de 17 de diciembre de 1979'),
(21,'Deportación a un lugar en el que se pueda sufrir violaciones a derechos humanos',2,''),
(22,'Violación sexual',2,''),
(23,'Arraigo',3,''),
(24,'Arresto domiciliario',3,''),
(25,'Detención arbitraria o ilegal',3,''),
(26,'Encarcelamiento arbitrario',3,''),
(27,'Reclutamiento forzoso',3,''),
(28,'Redada',3,''),
(29,'Revisión irregular o arbitraria',3,''),
(30,'Secuestro',3,''),
(31,'Toque de queda',3,''),
(32,'Esclavitud',4,''),
(33,'Prostitución forzada',4,''),
(34,'Servidumbre',4,''),
(35,'Trabajo forzoso',4,''),
(36,'Tráfico de personas',4,''),
(37,'Trata de personas',4,''),
(40,'Violaciones al derecho a ser comunicado(a)s con las autoridades consulares de su Estado en caso de ser detenido(a)s',5,'Violaciones a los derechos humanos y violación al derecho internacional'),
(53,'Derecho a un tribunal independiente e imparcial',6,'Violaciones a los derechos humanos y violación al derecho internacional'),
(60,'Extradición',6,''),
(70,'Extorsión',11,'Aplica a situaciones donde la autoridad o particulares utilizan de forma arbitraria o injustificada el poder (ya sea económico, político, etc.) que legalmente poseen. No se trata de actos ilegales, sino de que empleando sus facultades, las utilizan arbitrariamente, ejerciendo acciones innecesarias, intimidatorias con una gran carga de discrecionalidad. Ej. El caso del General Gallardo, al cual se le abrieron 13 averiguaciones previas, cada una después de una exoneración de la anterior. No puede hablarse de acciones ilegales, pero sí arbitrarias y discrecionales, con una intencionalidad de castigar. Otro ejemplo son los operativos injustificados o arbitrarios, que nuevamente no son ilegales porque la autoridad tiene facultades para realizar operativos, pero cuando se hacen sin causa que amerite el operativo, como denuncias específicas o pruebas de que es necesario el operativo, causan molestia a la población y pueden ser utilizados para intimidar a comunidades'),
(71,'Allanamiento',15,''),
(72,'Cateo',15,''),
(73,'Injerencias arbitrarias e ilegales en el domicilio',15,'Incluye injerencias arbitrarias e ilegales en comunidades'),
(74,'Violación a la confidencialidad de las comunicaciones',16,''),
(75,'Violación a la correspondencia',16,''),
(76,'Censura',17,''),
(77,'Restricciones para publicar o difundir información',17,'Ej. Recolectar o comprar todos los ejemplares de un periódico o una revista evitando el acceso a la misma'),
(78,'Negación de la existencia de información',18,''),
(79,'Retención de información',18,''),
(85,'Bloqueo de vías de comunicación',22,''),
(86,'Retenes',22,''),
(92,'Alto número de alumnos por maestro',35,''),
(93,'Ubicación de la escuela a gran distancia de la casa del o la estudiante',35,''),
(94,'Condiciones inadecuadas de escuelas y salones de clase',35,''),
(95,'Cuotas escolares prohibitivas',35,''),
(96,'Negación del tratamiento adecuado',36,''),
(97,'Atención primaria de salud no proporcionada a comunidades específicas',36,''),
(98,'Negación de subsidio a los servicios para personas que no pueden pagar la atención primaria a la salud',36,''),
(99,'Costos prohibitivos de la atención médica',36,''),
(102,'Falta de oportunidades de empleo',37,''),
(103,'Expropiación arbitraria de la vivienda',38,''),
(104,'Destrucción de vivienda',38,''),
(105,'Negación de escrituras de vivienda',38,''),
(106,'Desalojos forzosos o ilegales',38,''),
(107,'Exposición a sustancias peligrosas',41,''),
(108,'Contaminación',41,''),
(112,'Robo',46,''),
(113,'Expropiación arbitraria',46,''),
(114,'Negación de título de propiedad de la tierra',46,''),
(121,'Violaciones al derecho de los y las trabajadore(a)s la negociación colectiva',48,''),
(125,'Negación de indemnización por despido injustificado',48,''),
(126,'Despido injustificado',48,''),
(127,'Negación de vacaciones periódicas con goce de sueldo',48,''),
(128,'Negación del descanso, del tiempo libre y de la limitación razonable de la jornada laboral',48,''),
(129,'No pago de salarios',48,'');


INSERT INTO `idheasIkari`.`actosN3Catalogo`
(`actoN3Id`,
`descripcion`,
`actosN2Catalogo_actoN2Id`,
`notas`,
`derechosAfectadosN3Catalogo_derechoAfectadoN3Id`)
VALUES
(38,'Violaciones al derecho a examinar testigo(a)s o peritos (careos)',5,'',1),
(39,'Violaciones al derecho a hallarse presente en el proceso',5,'',2),
(41,'Violaciones al derecho a ser informado del cambio en su situación jurídica',5,'',4),
(42,'Violaciones al derecho a un juicio público',5,'',6),
(43,'Violaciones al derecho de audiencia en caso de expulsión',5,'',7),
(44,'Expulsión',5,'',7),
(45,'Violaciones a los derechos de lo(a)s acusado(a)s',5,'',8),
(46,'Violaciones al derecho a una defensa adecuada',5,'',9),
(47,'Igualdad entre las partes (Principio de)',5,'',10),
(48,'Violaciones al derecho al debido procedimiento de solicitud de refugio',5,'Los solicitantes de refugio deben contar con plenas salvaguardas
procedimentales, así como garantías en todas sus etapas. 
Dado que la decisión sobre la solicitud de asilo afecta los derechos fundamentales del individuo y una decisión errónea tiene graves consecuencias, las
garantías procesales son un elemento esencial en los procedimientos de
determinación del estatuto de refugiado. Las salvaguardas esenciales que deben estar disponibles para todos los solicitantes a lo largo del proceso
incluyen:

• a) Acceso a la información, en un idioma comprensible para el solicitante, sobre la naturaleza del proceso, así como sus derechos y
obligaciones durante el procedimiento.
• b) La posibilidad de entrar en contacto con el ACNUR o con otras entidades o personas (las ONG, abogados, etc.) que le den asesoría sobre el procedimiento o
representación legal. En aquellos casos en que la asistencia legal
gratuita esté disponible, los solicitantes de asilo deben tener acceso a
ella.
• c)  Ayuda de intérpretes calificados e imparciales, en caso de ser
necesario.
 Además, todos los solicitantes de asilo cuyas solicitudes sean
declaradas como no 
admisibles o rechazadas deben tener derecho a, por lo menos, una apelación o revisión completa de parte de un cuerpo independiente de la autoridad que tomó la decisión en primera instancia, así como el derecho de permanecer en el país mientras dure el proceso de apelación.',11),
(49,'Derecho a presentar pruebas',6,'',12),
(50,'Derecho a un juicio expedito',6,'',13),
(51,'Derecho a un recurso efectivo',6,'',14),
(52,'Derecho a un tribunal competente',6,'',15),
(54,'Derecho a un(a) fiscal imparcial y objetivo(a)',6,'',17),
(55,'Derecho al acceso al expediente administrativo',6,'',18),
(56,'Derecho de apelación',6,'',19),
(57,'Derecho a impugnar la legalidad de la detención',6,'',20),
(58,'Derecho a reparación por la detención arbitraria o ilegal',6,'',21),
(59,'Derecho de indemnización por error judicial',6,'',22),
(61,'Violaciones al derecho a interponer recursos internacionales por VDH y VDI',7,'',23),
(62,'Violaciones al derecho a la asistencia apropiada para acceder a la justicia',7,'',24),
(63,'Violaciones al derecho a la atención médica y sicológica de urgencia',7,'',25),
(64,'Violaciones al derecho a la coadyuvancia',7,'',26),
(65,'Violaciones al derecho a la consideración y atención especiales durante los procedimientos que evite la revictimización',7,'',27),
(66,'Violaciones al derecho a la protección contra actos de intimidación y represalia, para sí y su familia antes, durante y después de los procedimientos',7,'',28),
(67,'Violaciones al derecho a ser informado(a) sobre el desarrollo del proceso penal',7,'',29),
(68,'Violaciones al derecho a una reparación adecuada, efectiva y rápida del daño sufrido',7,'',30),
(69,'Violaciones al derecho al acceso a la información pertinente sobre las violaciones o delitos y mecanismos de reparación',7,'',31),
(80,'Violaciones al derecho a formar asociaciones',19,'',32),
(81,'Violaciones al derecho de afiliarse a asociaciones',19,'',33),
(82,'Violaciones al derecho a fundar una familia',20,'',34),
(83,'Violaciones al derecho a la unidad familiar',20,'',36),
(84,'Violaciones al derecho a la reunificación familiar',20,'',35),
(87,'Violaciones al derecho al acceso al procedimiento de asilo',24,'El acceso al procedimiento para la determinación de la condición de refugiado es un requisito esencial para hacer efectiva la protección internacional de los refugiados.
Este principio aplica sin importar el modo en que los solicitantes de asilo hayan llegado a la jurisdicción del Estado. Se debe reconocer como una solicitud de asilo cualquier expresión del solicitante de buscar el reconocimiento como refugiado, y esto debe iniciar la aplicación de la protección contra la devolución.
Por lo tanto, la disuasión o el rechazo de una solicitud no fundamentada implican una violación al principio de acceso al procedimiento. Asimismo, debe haber una distinción clara entre la negación de la admisibilidad,
la cual es de naturaleza formal, y las decisiones basadas en un examen de los méritos de la solicitud. 
Cualquier decisión al respecto debe tomarse dentro de un procedimiento ordinario de determinación del estatuto de refugiado; las solicitudes que no cumplen con los requerimientos de admisibilidad deben ser declaradas inadmisibles en vez de ser rechazadas por motivo de inadmisibilidad.',37),
(88,'Violaciones al derecho a la no devolución',24,'El acceso físico de los solicitantes al territorio del país en el cual esperan ser admitidos como refugiados, así como el acceso a los procedimientos para la determinación de la condición de refugiado son requisitos esenciales para hacer efectiva la protección internacional de los refugiados.Todos los países deben respetar el principio de no devolución.',38),
(89,'Violaciones al derecho a no ser sancionado por ingreso o presencia irregulares',24,'Todos los que presenten una solicitud deben ser admitidos al territorio y se les debe conceder el derecho temporal de permanecer ahí hasta que se haga una determinación final sobre la solicitud de refugio, sin importar si poseen documentos de identidad personal o de viaje o si éstos son falsos.',39),
(90,'Violaciones al derecho a la confidencialidad',24,'Los procedimientos de asilo deben respetar siempre la confidencialidad de todos los aspectos de una solicitud de asilo, incluyendo el hecho mismo de la presentación de la solicitud. No se debe compartir información alguna sobre la solicitud con el país de origen. La información proporcionada por un solicitante de asilo a las autoridades en el marco de un procedimiento de asilo es confidencial y solamente puede ser usada por las autoridades para los fines para los cuales fue solicitad a; es decir, para determinar la elegibilidad para la protección internacional. Como regla general, no se debe compartir información alguna con las autoridades del paí¬s de origen del solicitante, así¬ como tampoco se debe dar información a un tercer paí¬s sin el consentimiento expreso del individuo afectado. Éste debe dar su aprobación libremente y no bajo coacción.',40),
(91,'Violaciones al derecho al registro y la documentación',24,'En el caso de México, una FM3 de No inmigrante Refugiado (con derecho a trabajar en cualquier actividad siempre que sea lícita y honesta).',41),
(100,'Violaciones al derecho a la salud sexual y reproductiva',36,'',42),
(101,'Violaciones al derecho al consentimiento informado en tratamientos médicos' ,36,'',43),
(109,'Violaciones al derecho a la identidad cultural',44,'',44),
(110,'Violaciones al derecho a la protección de los intereses morales y materiales',44,'',45),
(111,'Violaciones al derecho a la preservación de la cultura',44,'',46),
(115,'Violaciones al derecho de las mujeres a gozar de permiso por maternidad',47,'',47),
(116,'Violaciones al derecho de las mujeres a la protección por embarazo',47,'',47),
(117,'Violaciones al derecho de las mujeres a no ser objeto de violencia económica por su género',47,'',49),
(118,'Violaciones al derecho de las mujeres a no ser objeto de violencia física por su género',47,'',50),
(119,'Violaciones al derecho de las mujeres a no ser objeto de violencia psicológica por su género',47,'',51),
(120,'Violaciones al derecho de las mujeres trabajadoras a la protección',47,'',52),
(122,'Violaciones al derecho de los y las trabajadore(a)s a la huelga',48,'',54),
(123,'Violaciones al derecho de los y las trabajadore(a)s a la democracia sindical',48,'',55),
(124,'Violaciones al derecho de los y las trabajadore(a)s a la sindicación',48,'',56),
(130,'Violaciones al derecho de las personas privadas de la libertad a instalaciones adecuadas',49,'',57),
(131,'Violaciones al derecho de las personas privadas de la libertad a trato digno y humano',49,'',57),
(132,'Violaciones al derecho de las personas privadas de la libertad a información sobre los reglamentos',49,'',59),
(133,'Violaciones al derecho de las personas privadas de la libertad a presentar quejas',49,'',60),
(134,'Violaciones al derecho de las personas privadas de la libertad a servicios médicos',49,'',61),
(135,'Violaciones al derecho de separación entre  procesado(a)s y sentenciado(a)s',49,'',62),
(136,'Violaciones al derecho de las personas sentenciadas a los beneficios de la preliberación',50,'',63),
(137,'Violaciones al derecho de las personas sentenciadas a un trabajo productivo y apropiado',50,'',64),
(138,'Violaciones al derecho de las personas LGBT a no ser objeto de violencia por su orientación sexual',51,'',65),
(139,'Violaciones al derecho de las niñas y los niños a expresarse y ser escuchada(o)s',52,'',66),
(140,'Violaciones al derecho de las niñas y los niños a jugar y descansar',52,'',67),
(141,'Violaciones al derecho de las niñas y los niños a la protección',52,'',68),
(142,'Violaciones al derecho de las niñas y los niños a no trabajar',52,'',69),
(143,'Violaciones al derecho de las niñas y los niños a no carearse con el inculpado(a) en caso que los pueda afectar',52,'',70),
(144,'Violaciones al derecho de las personas con discapacidad a beneficios sociales',53,'',71),
(145,'Violaciones al derecho de las personas con discapacidad a la asistencia',53,'',72),
(146,'Violaciones al derecho de las personas con discapacidad a la integración o reintegración social',53,'',73),
(147,'Violaciones al derecho de las personas con discapacidad al empleo adecuado',53,'',74),
(148,'Violaciones al derecho de las personas adultas mayores a la protección',54,'',75),
(149,'Violaciones al derecho a la prevención y protección contra el desplazamiento',55,'',76),
(150,'Violaciones al derecho de las personas desplazadas a la protección contra la destrucción, apropiación, ocupación o uso arbitrario e ilegal de sus bienes que hayan abandonado',55,'',77),
(151,'Violaciones al derecho de las personas desplazadas a la reunificación familiar',55,'',78),
(152,'Violaciones al derecho de las personas desplazadas a participar en la planificación y gestión de su reasentamiento',55,'',79),
(153,'Violaciones al derecho de las personas desplazadas a recibir asistencia a su regreso, reasentamiento y reintegración',55,'',80),
(154,'Violaciones al derecho de las personas desplazadas a recibir protección y asistencia humanitaria',55,'',81),
(155,'Violaciones al derecho de las personas desplazadas a la indemnización por desplazamiento',55,'',82),
(156,'Violaciones al derecho de las y los defensore(a)s a recibir financiamiento para la defensa y promoción de los derechos humanos',56,'',85),
(157,'Violaciones al derecho de las y los defensore(a)s a hacer críticas y propuestas en materia de derechos humanos',56,'',84),
(158,'Violaciones al derecho de las y los defensore(a)s a promover y procurar la protección y realización de los derechos humanos',56,'',83),
(159,'Violaciones al derechos de las y los consumidores a la protección de la salud y la seguridad',57,'',86),
(160,'Violaciones al derecho de las y los consumidores a la protección de los intereses económicos y sociales',57,'',87),
(161,'Violaciones al derecho de las y los consumidores a la información',57,'',88),
(162,'Violaciones al derecho de las y los consumidores a la educación y formación en materia de consumo',57,'',89),
(163,'Violaciones al derecho de las y los consumidores de representación, consulta y participación',57,'',90),
(164,'Violaciones al derecho de las y los consumidores a obtener protección ante cualquier situación que cause inferioridad, subordinación o indefensión',57,'',91),
(165,'Violaciones al derecho de las y los consumidores a la reparación de daños y prejuicios que les causen',57,'',92),
(166,'Violaciones al derecho de los pueblos indígenas a la autonomía política, económica y social',63,'',93),
(167,'Violaciones al derecho de los pueblos indígenas a la consulta y participación',63,'',94),
(168,'Violaciones al derecho de los pueblos indígenas a la jurisdicción indígena',63,'',95),
(169,'Violaciones al derecho de los pueblos indígenas a la personería jurídica',63,'',96),
(170,'Violaciones al derecho de los pueblos indígenas a la tierra y territorio',63,'',97),
(171,'Violaciones al derecho de los pueblos indígenas a su cultura, identidad y educación',63,'',98);

INSERT INTO `idheasIkari`.`actosN4Catalogo`
(`actoN4Id`,
`descripcion`,
`actosN3Catalogo_actoN3Id`)
VALUES
(1,'Muerte resultado de negligencia médica',9),
(2,'Muerte resultado de la aplicación de la tortura',10),
(3,'Muerte resultado del uso desproporcionado o indebido de la fuerza pública',10),
(4,'Amenazas',17),
(5,'Amenazas de muerte',17),
(6,'Hostigamiento',17),
(7,'Vigilancia',17),
(24,'Negativa, inadmisibilidad  de la solicitud de asilo',87),
(25,'Disuasión para no presentar una solicitud de asilo',87),
(26,'Rechazo de la solicitud de asilo no fundamentado',87),
(27,'Desinformación respecto del procedimiento de asilo',87),
(28,'No reconocimiento del estatuto de refugiado reconocido en otro país',87),
(29,'No acceso al procedimiento de asilo por considerar la solicitud manifiestamente infundada, abusiva o fraudulenta.',87);

INSERT INTO `idheasIkari`.`actosN4Catalogo`
(`actoN4Id`,
`descripcion`,
`actosN3Catalogo_actoN3Id`,
`derechosAfectadosN4Catalogo_derechoAfectadoN4Id`)
VALUES
(8,'Violaciones al derecho a ser informado(a) de las razones de la detención',45,1),
(9,'Violaciones al derecho a la libertad bajo fianza',45,2),
(10,'Violaciones al derecho a la no aplicación retroactiva de la ley en su perjuicio',45,3),
(11,'Violaciones al derecho a la presunción de inocencia',45,4),
(12,'Violaciones al derecho a no declarar en su contra',45,5),
(13,'Violaciones al derecho a no ser juzgado(a) dos veces por el mismo delito',45,6),
(14,'Violaciones al derecho a ser informado(a) de los cargos en su contra',45,7),
(15,'Violaciones al derecho a ser llevado(a) sin demora ante un(a) juez(a)',45,8),
(16,'Violaciones al derecho a ser procesado(a) sin demora o puesto(a) en libertad',45,9),
(17,'Violaciones al derecho a comunicarse con su defensor(a)',46,10),
(18,'Violaciones al derecho a disponer del tiempo y los medios adecuados para su defensa',46,11),
(19,'Violaciones al derecho a tener acceso a asistencia letrada durante el interrogatorio',46,12),
(20,'Violaciones al derecho a un defensor(a) de oficio',46,13),
(21,'Violaciones al derecho a un(a) intérprete',46,14),
(22,'Violaciones al derecho a una defensa eficaz',46,15),
(23,'Violaciones al derecho al defensor(a) de su elección',46,16),
(30,'Violaciones al derecho a no ser objeto de esterilización sin consentimiento informado',100,17),
(31,'Violaciones al derecho a no ser objeto de aborto forzado',100,18),
(32,'Violaciones al derecho a la interrupción del embarazo en casos permitidos por la ley',100,19),
(33,'Violaciones al derecho a planificar libremente los hijos que se desea tener',100,20),
(34,'Violaciones al derecho a los servicios de salud sexual y reproductiva',100,21);
